### ISSUE TITLE
Turn off labels display on results - custom drawing function?

### ISSUE THREAD

**Issue by Safeheaded** [Safeheaded/apples-recognition#4]

**Comment by Now4czyk** [comment]
Thread:
https://github.com/ultralytics/ultralytics/issues/499

Solution:
properties: hide_labels=True line_thickness=1

Implementation:
https://colab.research.google.com/drive/1LtxTVqjKDjaLY19FWP9unmWqTx2UQHZJ#scrollTo=YpyuwrNlXc1P

**Comment by Jaykumaran** [comment]
# Works also for Pose v8 models

from ultralytics import YOLO

# Load the YOLO model
model = YOLO('yolov8m-pose.pt')


# Perform object detection on the image
results = model(source='.jpg',save=True, conf=0.7,boxes=False,show_labels = False)
